export enum ErrorCode {
  ACCESS_POLICY_NOT_IMPLEMENTED = 'ACCESS_POLICY_NOT_IMPLEMENTED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  DATABASE_DUPLICATE_KEY = 'DATABASE_DUPLICATE_KEY',
  DATABASE_RECORD_NOT_FOUND = 'DATABASE_RECORD_NOT_FOUND',
  PASSWORD_CONFIRMATION_MISMATCH = 'PASSWORD_CONFIRMATION_MISMATCH',
  PASSWORD_RESET_OTP_INVALID = 'PASSWORD_RESET_OTP_INVALID',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}
